version: '2'
services:
  web:
    build: .
    ports:
      - "8083:8083"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: arjun
      MYSQL_USER: root
      MYSQL_PASSWORD: arjun
      MYSQL_DATABASE: root